### ISSUE TITLE
Include US region

### ISSUE THREAD

**Issue by kairoaraujo** [kairoaraujo/python-kodaksmarthome#4]
Implement US region.

**Comment by Gamerayers** [comment]
Is this support being worked on?  or has it been canceled?

**Comment by kairoaraujo** [comment]
Hi @Gamerayers it is still open but unfortunately I am not able to test once I'm in EU region. 

I see that someone forked my repo and did the change but someone needs to test. 

https://github.com/samuelhalle/python-kodaksmarthome/blob/5c6598c088f35399d94edf475633c0035ee6a88a/kodaksmarthome/constants.py#L22

If it works we could add and release new version.

**Comment by Gamerayers** [comment]
Hi @kairoaraujo I ran the install command on my raspberry pi 4 which is running home assistant, but I am not sure how to run the next set of commands.  I tend to be a little lost when it comes to the containers and pip world.  If you can let me know where to go from there, I can verify it and it can be committed then.

**Comment by kairoaraujo** [comment]
> `python3.8
> Python 3.8.5 (default, Jul 20 2020, 23:11:29)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from kodaksmarthome import KodakSmartHome
> > > > my_home = KodakSmartHome('#########@#####.com', '#######')
> > > > my_home.connect()

Hi @Gamerayers 

1. Edit the /usr/lib/python3.8/site-packages/kodaksmarthome/constants.py adding this block
```
# REGION_URLS
SUPPORTED_REGIONS = {
    "EU": {
        "URL": "https://app-eu.kodaksmarthome.com/web",
        "URL_TOKEN": "https://api-t01-r3.perimetersafe.com/v1/oauth/token",
        "URL_AUTH": "https://app-eu.kodaksmarthome.com/web/authenticate",
        "URL_DEVICES": "https://app-eu.kodaksmarthome.com/web/user/device",
        "URL_LOGOUT": "https://app-eu.kodaksmarthome.com/web/#/user/logout",
    },
    "US": {
        "URL": "https://app-us.kodaksmarthome.com/web",
        "URL_TOKEN": "https://api-t01-r3.perimetersafe.com/v1/oauth/token",
        "URL_AUTH": "https://app-us.kodaksmarthome.com/web/authenticate",
        "URL_DEVICES": "https://app-us.kodaksmarthome.com/web/user/device",
        "URL_LOGOUT": "https://app-us.kodaksmarthome.com/web/#/user/logout",
    }
}
```

2. try to use the 'US' region when you initiate the KodaSmartHome, adding region after the credentials, see example below.

```python

> Python 3.8.5 (default, Jul 20 2020, 23:11:29)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from kodaksmarthome import KodakSmartHome
> > > > my_home = KodakSmartHome('#########@#####.com', '#######', region='US')
> > > > my_home.connect()
```

**Comment by Gamerayers** [comment]
Looks like the same results.
I validated the https://app-us.kodaksmarthome.com/web connection with my same login and it worked just as a confirmation.

➜  ~ python3.8
Python 3.8.5 (default, Jul 20 2020, 23:11:29)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kodaksmarthome import KodakSmartHome
>>> my_home = KodakSmartHome('##@##.com', '##', region='US')
>>> my_home.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/kodaksmarthome/api.py", line 311, in connect
    self._token()
  File "/usr/lib/python3.8/site-packages/kodaksmarthome/api.py", line 194, in _token
    token_response = self._http_request(
  File "/usr/lib/python3.8/site-packages/kodaksmarthome/api.py", line 111, in _http_request
    raise ConnectionError(error_description)
ConnectionError: You entered an incorrect username or password. Check your sign in details and try again. Take note your account will be locked after next 4 failed attempt(s). Then you have to wait for 30 minutes to try again.

**Comment by raghavrithvik** [comment]
Hi,

Can we add HK region to this as well? When I tried logging in at 'https://app-eu.kodaksmarthome.com/web' it redirects to 'https://app-hk.kodaksmarthome.com/web/#/user/login'.

I assume just adding the following will make it work for the other regions.

# REGION_URLS
SUPPORTED_REGIONS = {
    "EU": {
        "URL": "https://app-eu.kodaksmarthome.com/web",
        "URL_TOKEN": "https://api-t01-r3.perimetersafe.com/v1/oauth/token",
        "URL_AUTH": "https://app-eu.kodaksmarthome.com/web/authenticate",
        "URL_DEVICES": "https://app-eu.kodaksmarthome.com/web/user/device",
        "URL_LOGOUT": "https://app-eu.kodaksmarthome.com/web/#/user/logout",
    },
  "US": {
        "URL": "https://app-us.kodaksmarthome.com/web",
        "URL_TOKEN": "https://api-t01-r3.perimetersafe.com/v1/oauth/token",
        "URL_AUTH": "https://app-us.kodaksmarthome.com/web/authenticate",
        "URL_DEVICES": "https://app-us.kodaksmarthome.com/web/user/device",
        "URL_LOGOUT": "https://app-us.kodaksmarthome.com/web/#/user/logout",
    },
    "HK": {
        "URL": "https://app-hk.kodaksmarthome.com/web",
        "URL_TOKEN": "https://api-t01-r3.perimetersafe.com/v1/oauth/token",
        "URL_AUTH": "https://app-hk.kodaksmarthome.com/web/authenticate",
        "URL_DEVICES": "https://app-hk.kodaksmarthome.com/web/user/device",
        "URL_LOGOUT": "https://app-hk.kodaksmarthome.com/web/#/user/logout",
    }
}
